import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const GENERATED_NOTE = "# Generated by NEUTRON demo (scaffold)";

export type DemoProject = "taskflow";

interface Files {
  [path: string]: string;
}

const TASKFLOW: Files = {
  "package.json": JSON.stringify(
    {
      name: "taskflow",
      version: "1.0.0",
      private: true,
      type: "module",
      scripts: { dev: "node server.js", start: "node server.js", test: "vitest run", build: "node server.js --check" },
      dependencies: {
        express: "^4.19.2",
        "express-session": "^1.18.0",
        bcryptjs: "^2.4.3",
        jsonwebtoken: "^9.0.2",
        "dotenv": "^16.4.1",
        "passport": "^0.7.0",
        "passport-google-oauth20": "^2.0.0",
      },
      devDependencies: { vitest: "^2.1.0" },
    },
    null,
    2,
  ),
  "README.md": [
    "# TaskFlow",
    "",
    "A task management app with email/password login, user profiles and a REST API.",
    "",
    "Stack: React, Node.js, Express, PostgreSQL.",
  ].join("\n"),
  ".env.example": [
    "SESSION_SECRET=change-me",
    "DATABASE_URL=postgres://user:pass@localhost:5432/taskflow",
    "JWT_SECRET=change-me",
    "GOOGLE_CLIENT_ID=",
    "GOOGLE_CLIENT_SECRET=",
  ].join("\n"),
  "server.js": `const express = require("express");
const session = require("express-session");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(
  session({
    secret: process.env.SESSION_SECRET || "dev-secret",
    resave: false,
    saveUninitialized: false,
  })
);

app.get("/health", (req, res) => res.json({ ok: true }));

const authRoutes = require("./src/routes/auth");
app.use("/api/auth", authRoutes);

const userRoutes = require("./src/routes/users");
app.use("/api/users", userRoutes);

const taskRoutes = require("./src/routes/tasks");
app.use("/api/tasks", taskRoutes);

module.exports = app;
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(\`TaskFlow listening on :\${PORT}\`));
`,
  "src/config/index.js": `const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "..", "..", ".env") });

module.exports = {
  sessionSecret: process.env.SESSION_SECRET || "dev-secret",
  jwtSecret: process.env.JWT_SECRET || "dev-jwt",
  databaseUrl: process.env.DATABASE_URL || "postgres://localhost:5432/taskflow",
  google: {
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    callbackUrl: process.env.GOOGLE_CALLBACK_URL || "http://localhost:3000/api/auth/google/callback",
  },
};
`,
  "src/middleware/auth.js": `const { verifyToken } = require("../services/token");

function requireAuth(req, res, next) {
  const header = req.headers.authorization || "";
  const token = header.startsWith("Bearer ") ? header.slice(7) : null;
  if (!token) return res.status(401).json({ error: "Unauthorized" });
  try {
    req.user = verifyToken(token);
    next();
  } catch (err) {
    return res.status(401).json({ error: "Invalid session" });
  }
}

module.exports = { requireAuth };
`,
  "src/services/token.js": `const jwt = require("jsonwebtoken");
const { jwtSecret } = require("../config");

function issueToken(user) {
  return jwt.sign({ id: user.id, email: user.email }, jwtSecret, { expiresIn: "7d" });
}

function verifyToken(token) {
  return jwt.verify(token, jwtSecret);
}

module.exports = { issueToken, verifyToken };
`,
  "src/services/password.js": `const bcrypt = require("bcryptjs");

async function hash(plain) {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(plain, salt);
}

async function verify(plain, hashed) {
  return bcrypt.compare(plain, hashed);
}

module.exports = { hash, verify };
`,
  "src/services/users.js": `const users = require("../db/users");

async function createUser({ email, password }) {
  const existing = await users.findByEmail(email);
  if (existing) throw new Error("EMAIL_TAKEN");
  return users.insert({ email, password });
}

async function findById(id) {
  return users.findById(id);
}

module.exports = { createUser, findById };
`,
  "src/routes/auth.js": `const express = require("express");
const router = express.Router();
const passport = require("passport");
const { issueToken } = require("../services/token");
const { verify } = require("../services/password");
const users = require("../db/users");

router.post("/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await users.findByEmail(email);
    if (!user) return res.status(401).json({ error: "Invalid credentials" });
    const ok = await verify(password, user.passwordHash);
    if (!ok) return res.status(401).json({ error: "Invalid credentials" });
    res.json({ token: issueToken(user), user: { id: user.id, email: user.email } });
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

router.post("/register", async (req, res) => {
  try {
    const { email, password } = req.body;
    const hashService = require("../services/password");
    const passwordHash = await hashService.hash(password);
    const user = await users.insert({ email, passwordHash });
    res.status(201).json({ user: { id: user.id, email: user.email } });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.get("/google", passport.authenticate("google", { scope: ["profile", "email"] }));
router.get(
  "/google/callback",
  passport.authenticate("google", { failureRedirect: "/login" }),
  (req, res) => {
    const token = issueToken(req.user);
    res.json({ token, user: { id: req.user.id, email: req.user.email } });
  }
);

module.exports = router;
`,
  "src/routes/users.js": `const express = require("express");
const router = express.Router();
const { requireAuth } = require("../middleware/auth");
const { findById } = require("../services/users");

router.get("/me", requireAuth, async (req, res) => {
  const user = await findById(req.user.id);
  res.json({ user });
});

router.put("/me", requireAuth, async (req, res) => {
  const user = await findById(req.user.id);
  res.json({ user: { ...user, ...req.body } });
});

module.exports = router;
`,
  "src/routes/tasks.js": `const express = require("express");
const router = express.Router();
const { requireAuth } = require("../middleware/auth");
const tasks = require("../db/tasks");

router.get("/", requireAuth, async (req, res) => {
  const items = await tasks.listByUser(req.user.id);
  res.json({ tasks: items });
});

router.post("/", requireAuth, async (req, res) => {
  const task = await tasks.insert({ ownerId: req.user.id, title: req.body.title });
  res.status(201).json({ task });
});

module.exports = router;
`,
  "src/db/index.js": `const { databaseUrl } = require("../config");

// In-memory + environment-driven store for the demo. Production would use PostgreSQL.
const MAP = new Map();

function init() {
  void databaseUrl;
}

module.exports = { MAP, init };
`,
  "src/db/users.js": `const { MAP } = require("./index");

const users = [];

async function findByEmail(email) {
  return users.find((u) => u.email === email) || null;
}

async function findById(id) {
  return users.find((u) => u.id === id) || null;
}

async function insert({ email, passwordHash }) {
  const user = { id: users.length + 1, email, passwordHash, createdAt: new Date().toISOString() };
  users.push(user);
  return user;
}

module.exports = { findByEmail, findById, insert };
`,
  "src/db/tasks.js": `const tasks = [];

async function listByUser(ownerId) {
  return tasks.filter((t) => t.ownerId === ownerId);
}

async function insert({ ownerId, title }) {
  const task = { id: tasks.length + 1, ownerId, title, done: false, createdAt: new Date().toISOString() };
  tasks.push(task);
  return task;
}

module.exports = { listByUser, insert };
`,
  "src/frontend/pages/Login.jsx": `import React, { useState } from "react";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  async function submit() {
    const res = await fetch("/api/auth/login", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ email, password }),
    });
    if (res.ok) {
      window.location.href = "/dashboard";
    }
  }

  return (
    <div>
      <h1>Login</h1>
      <input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="email" />
      <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="password" />
      <button onClick={submit}>Sign in</button>
      <a href="/api/auth/google">Continue with Google</a>
    </div>
  );
}
`,
  "src/frontend/pages/Dashboard.jsx": `import React, { useEffect, useState } from "react";

export default function Dashboard() {
  const [tasks, setTasks] = useState([]);
  useEffect(() => {
    fetch("/api/tasks")
      .then((r) => r.json())
      .then((d) => setTasks(d.tasks));
  }, []);
  return (
    <div>
      <h1>Dashboard</h1>
      <ul>{tasks.map((t) => <li key={t.id}>{t.title}</li>)}</ul>
    </div>
  );
}
`,
  "src/frontend/pages/Profile.jsx": `import React, { useEffect, useState } from "react";

export default function Profile() {
  const [user, setUser] = useState(null);
  useEffect(() => {
    fetch("/api/users/me")
      .then((r) => r.json())
      .then((d) => setUser(d.user));
  }, []);
  return <div><h1>Profile</h1>{user && <p>{user.email}</p>}</div>;
}
`,
  "src/frontend/services/api.js": `export async function api(path, options = {}) {
  const res = await fetch(path, {
    ...options,
    headers: { "content-type": "application/json", ...(options.headers || {}) },
  });
  if (!res.ok) throw new Error("Request failed");
  return res.json();
}
`,
  "tests/auth.test.js": `const { describe, it, expect } = require("vitest");
const request = require("supertest");
const app = require("../server");
const users = require("../src/db/users");

describe("auth", () => {
  it("registers a user", async () => {
    const res = await request(app).post("/api/auth/register").send({ email: "a@b.c", password: "secret123" });
    expect(res.statusCode).toBe(201);
  });
  it("logs in with valid credentials", async () => {
    await request(app).post("/api/auth/register").send({ email: "a@b.c", password: "secret123" });
    const res = await request(app).post("/api/auth/login").send({ email: "a@b.c", password: "secret123" });
    expect(res.statusCode).toBe(200);
    expect(res.body.token).toBeTruthy();
  });
  it("rejects invalid credentials", async () => {
    const res = await request(app).post("/api/auth/login").send({ email: "a@b.c", password: "wrong" });
    expect(res.statusCode).toBe(401);
  });
});
`,
  "tests/tasks.test.js": `const { describe, it, expect } = require("vitest");
const request = require("supertest");
const app = require("../server");
const { issueToken } = require("../src/services/token");

describe("tasks", () => {
  it("requires auth", async () => {
    const res = await request(app).get("/api/tasks");
    expect(res.statusCode).toBe(401);
  });
  it("lists and creates tasks with a token", async () => {
    const token = issueToken({ id: 1, email: "a@b.c" });
    const create = await request(app).post("/api/tasks").set("authorization", \`Bearer \${token}\`).send({ title: "Do it" });
    expect(create.statusCode).toBe(201);
    const list = await request(app).get("/api/tasks").set("authorization", \`Bearer \${token}\`);
    expect(list.statusCode).toBe(200);
  });
});
`,
  "tests/security.test.js": `const { describe, it, expect } = require("vitest");

describe("security posture", () => {
  it("uses safe password hashing", async () => {
    const pw = require("../src/services/password");
    const hash = await pw.hash("secret123");
    expect(hash).not.toContain("secret123");
    expect(await pw.verify("secret123", hash)).toBe(true);
  });
});
`,
};

export function scaffoldDemoProject(root: string, project: DemoProject = "taskflow"): { files: string[]; warning?: string } {
  const files = TASKFLOW;
  const written: string[] = [];
  for (const [rel, content] of Object.entries(files)) {
    const target = join(root, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, "utf8");
    written.push(rel);
  }
  const note = join(root, "NEUTRON_DEMO.md");
  writeFileSync(note, `${GENERATED_NOTE}\nDemo project: TaskFlow\n`, "utf8");
  written.push("NEUTRON_DEMO.md");
  return { files: written };
}

export const DEMO_REQUESTS: Record<DemoProject, string> = {
  taskflow: "Add Google OAuth while preserving the existing email/password login.",
};

export const DEMO_DESCRIPTIONS: Record<DemoProject, string> = {
  taskflow: "TaskFlow — a task management app with email/login, user profiles, a REST API and tests. Add Google OAuth.",
};